### ISSUE TITLE
Séquencer déploiements albert API

### ISSUE THREAD

**Issue by ArtixJP** [etalab-ia/OpenGateLLM#55]
# Problème 

En tant qu'administration utilisatrice d'Albert API, j'ai besoin d'une certaine garantie de service et de communication sur les déploiements effectués.

En tant que Product Manager, j'ai besoin de savoir quand est-ce que je me mets en marche pour faire des tests fonctionnels.

# Solution 

- [x] etalab-ia/albert-api#81
- [x] etalab-ia/albert-api#59
- [x] etalab-ia/albert-api#60
- [x] etalab-ia/albert-api#62
- [x] etalab-ia/albert-api#63
